apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-router
  name: mongo-router-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo-router
  type: NodePort

