auth:
  enabled: true
  rootUser: root
  rootPassword: "root"

shards: 2

configsvr:
  replicaCount: 3
  mongodbExtraFlags:
    # because docker may be offline for a while
    - "--setParameter rollbackTimeLimitSecs=10000000"

mongos:
  replicaCount: 3

shardsvr:
  dataNode:
    replicaCount: 3
  
  persistence:
    size: 8Gi
  
  arbiter:
    replicaCount: 0

metrics:
  enabled: true
  podMonitor:
    enabled: true
    namespace: mongodb
